#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Linux" ]; then

  # update system
  apt update && apt -y upgrade && apt -y autoremove && apt -y autoclean
  
  # install git if it is missing
  if ! command -v bat >/dev/null 2>&1; then
    echo "Installing git"
     apt -y install git
  fi

  # install curl if it is missing
  if ! command -v curl >/dev/null 2>&1; then
    echo "Installing curl"
     apt -y install curl
  fi

  # install python3 if it is missing
  if ! command -v python3 >/dev/null 2>&1; then
    echo "Installing python 3"
     apt -y install python3
  fi
  
  # install neovim if it's missing
  if ! command -v nvim >/dev/null 2>&1; then
    echo "Installing Neovim"
     apt -y install neovim 
  fi
 
  # install exa if it's missing
  if ! command -v exa >/dev/null 2>&1; then
    echo "Installing exa"
     apt -y install exa 
  fi

  # install gpg if it is missing
  if ! command -v gpg >/dev/null 2>&1; then
    echo "Installing gpg"
     apt -y install gpg 
  fi

  # install bat if it is missing
  if ! command -v bat >/dev/null 2>&1; then
    echo "Installing bat"
     apt -y install bat 
  fi
  
  # install command-not-found if it is missing
  if ! command -v command-not-found >/dev/null 2>&1; then
    echo "Installing command-not-found"
     apt -y install command-not-found
     apt update
     update-command-not-found
  fi

  # install zsh-autosuggestions if it is missing
  if [ ! -f "/opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh" ]; then
    echo "Installing zsh-autosuggestions" 
     apt -y install zsh-autosuggestions
  fi

  # install zsh-syntax-highlighting if it is missing
  if [ ! -f "/opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then
    echo "Installing zsh-syntax-highlighting" 
     apt -y install zsh-syntax-highlighting
  fi
  
  # install zsh-completions if it is missing
  if [ ! -d "/opt/homebrew/share/zsh-completions" ]; then
    echo "Installing zsh-completions" 
     apt -y install zsh-completions
  fi

fi


if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
  
  # install neovim if it's missing
  if ! command -v nvim >/dev/null 2>&1; then
    echo "Installing Neovim"
    brew install nvim 
  fi
 
  # install exa if it's missing
  if ! command -v exa >/dev/null 2>&1; then
    echo "Installing exa"
    brew install exa 
  fi

  # install gpg if it is missing
  if ! command -v gpg >/dev/null 2>&1; then
    echo "Installing gpg"
    brew install gpg 
  fi

  # install bat if it is missing
  if ! command -v bat >/dev/null 2>&1; then
    echo "Installing bat"
    brew install bat 
  fi

  # install zsh-autosuggestions if it is missing
  if [ ! -f "/opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh" ]; then
    echo "Installing zsh-autosuggestions" 
    brew install zsh-autosuggestions
  fi

  # install zsh-syntax-highlighting if it is missing
  if [ ! -f "/opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then
    echo "Installing zsh-syntax-highlighting" 
    brew install zsh-syntax-highlighting
  fi
  
  # install zsh-completions if it is missing
  if [ ! -d "/opt/homebrew/share/zsh-completions" ]; then
    echo "Installing zsh-completions" 
    brew install zsh-completions
  fi
  
  if ! command -v command-not-found >/dev/null 2>&1; then
    echo "Installing command-not-found"
     brew install command-not-found
     update-command-not-found
  fi
 
  if ! mdfind "kMDItemCFBundleIdentifier == com.googlecode.iterm2" >/dev/null 2>&1; then
    echo "Installing iTerm2" 
    brew cask install iterm2
  fi

  if [ -d "$HOME/.config/iTerm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iTerm2"
  fi
fi

# install oh-my-zsh if it is missing

if [ -d "$HOME/.oh-my-zsh" ]; then
  echo "Install oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi
  
echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:Instagraeme/latest-dotfiles.git"

if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping neovim"
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
